CREATE TABLE `irmr_term_taxonomy` (  `term_taxonomy_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,  `term_id` bigint(20) unsigned NOT NULL DEFAULT '0',  `taxonomy` varchar(32) NOT NULL DEFAULT '',  `description` longtext NOT NULL,  `parent` bigint(20) unsigned NOT NULL DEFAULT '0',  `count` bigint(20) NOT NULL DEFAULT '0',  PRIMARY KEY (`term_taxonomy_id`),  UNIQUE KEY `term_id_taxonomy` (`term_id`,`taxonomy`),  KEY `taxonomy` (`taxonomy`)) ENGINE=InnoDB AUTO_INCREMENT=23 DEFAULT CHARSET=utf8;
/*!40000 ALTER TABLE `irmr_term_taxonomy` DISABLE KEYS */;
INSERT INTO `irmr_term_taxonomy` VALUES('1', '1', 'category', '', '0', '3');
INSERT INTO `irmr_term_taxonomy` VALUES('2', '2', 'nav_menu', '', '0', '30');
INSERT INTO `irmr_term_taxonomy` VALUES('3', '3', 'nav_menu', '', '0', '4');
INSERT INTO `irmr_term_taxonomy` VALUES('4', '4', 'nav_menu', '', '0', '5');
INSERT INTO `irmr_term_taxonomy` VALUES('5', '5', 'nav_menu', '', '0', '11');
INSERT INTO `irmr_term_taxonomy` VALUES('6', '6', 'nav_menu', '', '0', '2');
INSERT INTO `irmr_term_taxonomy` VALUES('7', '7', 'nav_menu', '', '0', '11');
INSERT INTO `irmr_term_taxonomy` VALUES('8', '8', 'category', '', '0', '0');
INSERT INTO `irmr_term_taxonomy` VALUES('9', '9', 'post_format', '', '0', '1');
INSERT INTO `irmr_term_taxonomy` VALUES('10', '10', 'category', '', '0', '0');
INSERT INTO `irmr_term_taxonomy` VALUES('11', '11', 'publications', '', '0', '2');
INSERT INTO `irmr_term_taxonomy` VALUES('12', '12', 'category', '', '0', '1');
INSERT INTO `irmr_term_taxonomy` VALUES('13', '13', 'category', '', '0', '0');
INSERT INTO `irmr_term_taxonomy` VALUES('14', '14', 'category', '', '0', '2');
INSERT INTO `irmr_term_taxonomy` VALUES('15', '15', 'category', '', '0', '1');
INSERT INTO `irmr_term_taxonomy` VALUES('16', '16', 'publications', '', '0', '1');
INSERT INTO `irmr_term_taxonomy` VALUES('17', '17', 'publications', '', '0', '1');
INSERT INTO `irmr_term_taxonomy` VALUES('18', '18', 'publications', '', '0', '1');
INSERT INTO `irmr_term_taxonomy` VALUES('19', '19', 'publications', '', '0', '1');
INSERT INTO `irmr_term_taxonomy` VALUES('20', '20', 'publications', '', '0', '1');
INSERT INTO `irmr_term_taxonomy` VALUES('21', '21', 'publications', '', '0', '1');
INSERT INTO `irmr_term_taxonomy` VALUES('22', '22', 'nav_menu', '', '0', '3');
/*!40000 ALTER TABLE `irmr_term_taxonomy` ENABLE KEYS */;
