CREATE TABLE `irmr_terms` (  `term_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,  `name` varchar(200) NOT NULL DEFAULT '',  `slug` varchar(200) NOT NULL DEFAULT '',  `term_group` bigint(10) NOT NULL DEFAULT '0',  PRIMARY KEY (`term_id`),  KEY `slug` (`slug`),  KEY `name` (`name`)) ENGINE=InnoDB AUTO_INCREMENT=23 DEFAULT CHARSET=utf8;
/*!40000 ALTER TABLE `irmr_terms` DISABLE KEYS */;
INSERT INTO `irmr_terms` VALUES('1', 'Uncategorized', 'uncategorized', '0');
INSERT INTO `irmr_terms` VALUES('2', 'Primary Menu', 'primary-menu', '0');
INSERT INTO `irmr_terms` VALUES('3', 'Footer Menu', 'footer-menu', '0');
INSERT INTO `irmr_terms` VALUES('4', 'Experience Sidenav', 'experience-sidenav', '0');
INSERT INTO `irmr_terms` VALUES('5', 'Activity Sidenav', 'activity-sidenav', '0');
INSERT INTO `irmr_terms` VALUES('6', 'Lodging Sidenav', 'lodging-sidenav', '0');
INSERT INTO `irmr_terms` VALUES('7', 'Dining Sidenav', 'dining-sidenav', '0');
INSERT INTO `irmr_terms` VALUES('8', '2010 Showcase Speakers', '2010-showcase-speakers', '0');
INSERT INTO `irmr_terms` VALUES('9', 'Gallery', 'post-format-gallery', '0');
INSERT INTO `irmr_terms` VALUES('10', 'history', 'history', '0');
INSERT INTO `irmr_terms` VALUES('11', 'New York Times', 'new-york-times', '0');
INSERT INTO `irmr_terms` VALUES('12', 'dining', 'dining', '0');
INSERT INTO `irmr_terms` VALUES('13', 'music', 'music', '0');
INSERT INTO `irmr_terms` VALUES('14', 'holiday', 'holiday', '0');
INSERT INTO `irmr_terms` VALUES('15', 'hiking', 'hiking', '0');
INSERT INTO `irmr_terms` VALUES('16', 'Sunset Magazine', 'sunset-magazine', '0');
INSERT INTO `irmr_terms` VALUES('17', 'Travel &amp; Leisure', 'travel-and-leisure', '0');
INSERT INTO `irmr_terms` VALUES('18', 'Los Angeles Times', 'los-angeles-times', '0');
INSERT INTO `irmr_terms` VALUES('19', 'Washington Post', 'washington-post', '0');
INSERT INTO `irmr_terms` VALUES('20', 'Sun Valley Property News', 'sun-valley-property-news', '0');
INSERT INTO `irmr_terms` VALUES('21', 'Sun Valley Magazine', 'sun-valley-magazine', '0');
INSERT INTO `irmr_terms` VALUES('22', 'Employment Sidenav', 'employment-sidenav', '0');
/*!40000 ALTER TABLE `irmr_terms` ENABLE KEYS */;
